---
# inventories/group_vars/static.yml
all:
  hosts:
    node1:
      ansible_host: 192.168.56.10
    node2:
      ansible_host: 192.168.56.11
    node3:
      ansible_host: 192.168.56.12
  children:
    logging:
      children:
        mongodb:
          hosts:
            node1:
            node2:
            node3:
        elastic:
          hosts:
            node1:
            node2:
            node3:
        graylog:
          hosts:
            node1:
            node2:
