---
# file: inventories/group_vars/elastic/vars.yml
elastic_firewall:
  enabled: true
  rules:
    - { port: "9200", direction: "in", protocol: "tcp", policy: "allow", description: "ElasticSearch HTTP" }
    - { port: "9300", direction: "in", protocol: "any", policy: "allow", description: "ElasticSearch Transport" }

elastic_roles:
  admin:
    cluster:
      - all
    indices:
      - names: "*"
        privileges:
          - all
  program:
    indices:
      - names: "{{ graylog_elasticsearch_index_prefix }}*"
        privileges:
          - all

elastic_users:
  - name: admin
    password: "{{ vault_elastic_admin_passwd }}"
    roles:
      - admin
  - name: graylog
    password: "{{ vault_elastic_graylog_passwd }}"
    roles:
      - program