---
# file: roles/graylog/tasks/configure.yml
- name: Generate root password
  shell: 'echo {{ vault_graylog_root_passwd }} | tr -d "\n" | sha256sum | cut -d" " -f1'
  register: sha256_root_passwd
  tags: configure

- name: Configure Graylog
  become: yes
  template:
    src: server.conf.j2
    dest: "{{ graylog_conf_path }}/server.conf"
    owner: "{{ graylog_user }}"
    group: "{{ graylog_group }}"
    mode: 0644
  notify: restart graylog
  tags: configure