---
# file: roles/graylog/tasks/main.yml
- name: Install Graylog
  include_tasks: install.yml
  when: "'graylog-server' not in ansible_facts.packages"

- name: Configure Graylog
  include_tasks: configure.yml
  tags: configure