---
# file: roles/basic/tasks/main.yml
- name: Get package facts
  become: yes
  package_facts:
    manager: "apt"

- name: Install packages
  become: yes
  apt:
    name: "{{ basic_packages }}"
    update_cache: yes
    cache_valid_time: 86400