---
# file: roles/elastic_search/defaults/main.yml
elastic:
  version: 6.8.8
  cluster_name: graylog
  data_path: /var/data/elasticsearch
  log_path: /var/log/elasticsearch
  bind_host: "{{ ansible_host }}"
  http_port: 9200
  transport_port: 9300