---
# file: roles/elastic/meta/main.yml
galaxy_info:
  role_name: elastic
  author: Romanov Alex <romanowalex@mail.ru>
  license: EULA
  platforms:
    - name: Ubuntu
      versions:
        - 18.04
dependencies:
  - basic
  - firewall
  - galaxy-elastic